# Site settings
title: G-Türk İHA
email: gturkiha@gmail.com
url: https://www.gturkiha.com
description: "G-Türk İHA Takımı, Gebze Teknik Üniversitesi'nde havacılığa ilgi duyan bir
                grup arkadaş tarafından kurulmuştur. Ar-Ge çalışmaları düzenli olarak devam etmektedir"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#2bf0e3'

# Footer settings
footer: gturkiha.com

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: instagram
    url: https://www.instagram.com/gturkiha/
  - title: linkedin
    url: https://www.linkedin.com/company/g-turk-i%CC%87ha
  - title: youtube
    url: https://www.youtube.com/channel/UC1LD4CbryaYLpeAlETrts9g

# Build settings
markdown: kramdown
permalink: pretty
